### ISSUE TITLE
AttributeError: module 'tensorflow_federated.python.core.backends.native' has no attribute 'set_sync_local_execution_context'

### ISSUE THREAD

**Issue by deepquantum88** [tensorflow/federated#3792]
**Describe the bug**
Trying to run TFF with differential privacy module, but it throws an attribute error.

**Environment (please complete the following information):**
* python=3.8.16
* Tensorflow: 2.7.0
* TFF: 0.19.0

I cannot use python 3.9 or TF >2.7.0 due to compatibility with other packages. How can i use module 'tensorflow_federated.python.core.backends.native'  'set_sync_local_execution_context'. Is there any alternative or am missing something. Please help.

**Comment by huili0140** [comment]
Thank you for the question, we're looking into this.

**Comment by huili0140** [comment]
Hi, it looks like the TFF version you used is an very old version, it's a version we released about 2 years ago. The TFF tutorials and TFF API docs are all based on the newer versions. Are you copying the tutorial from Colab and run it locally?

**Comment by deepquantum88** [comment]
Hi, I tried tff.aggregator differential privacy from https://www.tensorflow.org/federated/tutorials/tuning_recommended_aggregators

But it did not work.

I seen in github tff release that tff.aggregators can work in tff 2.19.0 version and tf 2.7.0 and python 3.8.16.
https://github.com/tensorflow/federated/blob/main/RELEASE.md

dp_mean = tff.aggregators.DifferentiallyPrivateFactory.gaussian_adaptive(
    noise_multiplier=0.1, clients_per_round=100)

But it throws an error that tff has no attribute aggregators. 

Else what can be the minimum version of tff to work with aggregators. 

can you please look in to this.

**Comment by deepquantum88** [comment]
@zcharles8 
I tried to execute tff.learning.dp_aggregator in aggregator. But when i initialize iterative process, it stuck (like in loop)

dp_mean = tff.aggregators.DifferentiallyPrivateFactory.gaussian_adaptive(
    noise_multiplier=0.1, clients_per_round=4)

iterative_process = tff.learning.algorithms.build_unweighted_fed_avg(
        my_model_fn,
        client_optimizer_fn=lambda: tf.keras.optimizers.SGD(0.01),
        server_optimizer_fn=lambda: tf.keras.optimizers.SGD(1.0, momentum=0.9),
        model_aggregator=dp_mean)

  state = iterative_process.initialize()

When i am executing the above initialize statement, it keeps on executing and look like in infinite loop.

Python=3.9.7
TF=2.11.0
TFF=0.48.0
